### ISSUE TITLE
error of reduce_dimension in monocle3

### ISSUE THREAD

**Issue by Shawn10312** [cole-trapnell-lab/monocle3#356] opened 2020-05-23 03:50 UTC
Hi,
I confront a error when following the pipeline of monocle3 in https://cole-trapnell-lab.github.io/monocle3/docs/clustering/.
```
> cds <- reduce_dimension(cds)
No preprocess_method specified, using preprocess_method = 'PCA'
Error in x2set(Xsub, n_neighbors, metric, nn_method = nn_sub, n_trees,  : 
  Non-finite entries in the input matrix
```

```
> Sys.info()
                              sysname                               release 
                              "Linux"          "3.10.0-957.38.1.el7.x86_64" 
                              version                              nodename 
"#1 SMP Thu Sep 26 12:15:44 EDT 2019"     "c18n06.ruddle.hpc.yale.internal" 
                              machine                                 login 
                             "x86_64"                             "unknown" 
                                 user                        effective_user 
                              "yx358"                               "yx358" 
> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.6 (Maipo)

Matrix products: default
BLAS/LAPACK: /gpfs/ycga/apps/hpc/software/OpenBLAS/0.3.1-GCC-7.3.0-2.30/lib/libopenblas_haswellp-r0.3.1.so

locale:
[1] en_US.UTF-8

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] dplyr_0.8.5                 ggplot2_3.3.0               monocle3_0.2.1             
 [4] SingleCellExperiment_1.8.0  SummarizedExperiment_1.16.1 DelayedArray_0.12.3        
 [7] BiocParallel_1.20.1         matrixStats_0.56.0          GenomicRanges_1.38.0       
[10] GenomeInfoDb_1.22.1         IRanges_2.20.2              S4Vectors_0.24.4           
[13] Biobase_2.46.0              BiocGenerics_0.32.0         Seurat_3.1.5               

loaded via a namespace (and not attached):
 [1] nlme_3.1-147             tsne_0.1-3               bitops_1.0-6            
 [4] RcppAnnoy_0.0.16         RColorBrewer_1.1-2       httr_1.4.1              
 [7] sctransform_0.2.1        tools_3.6.1              R6_2.4.1                
[10] irlba_2.3.3              KernSmooth_2.23-16       uwot_0.1.8              
[13] lazyeval_0.2.2           colorspace_1.4-1         withr_2.2.0             
[16] npsurv_0.4-0             tidyselect_1.1.0         gridExtra_2.3           
[19] compiler_3.6.1           plotly_4.9.2.1           labeling_0.3            
[22] caTools_1.18.0           scales_1.1.1             lmtest_0.9-37           
[25] ggridges_0.5.2           pbapply_1.4-2            rappdirs_0.3.1          
[28] stringr_1.4.0            digest_0.6.25            XVector_0.26.0          
[31] pkgconfig_2.0.3          htmltools_0.4.0          htmlwidgets_1.5.1       
[34] rlang_0.4.6              rstudioapi_0.11          DelayedMatrixStats_1.8.0
[37] zoo_1.8-8                jsonlite_1.6.1           ica_1.0-2               
[40] gtools_3.8.2             RCurl_1.98-1.2           magrittr_1.5            
[43] GenomeInfoDbData_1.2.2   patchwork_1.0.0          Matrix_1.2-18           
[46] Rcpp_1.0.4.6             munsell_0.5.0            viridis_0.5.1           
[49] ape_5.3                  reticulate_1.15          lifecycle_0.2.0         
[52] stringi_1.4.6            yaml_2.2.1               zlibbioc_1.32.0         
[55] MASS_7.3-51.5            gplots_3.0.3             Rtsne_0.15              
[58] plyr_1.8.6               grid_3.6.1               gdata_2.18.0            
[61] listenv_0.8.0            ggrepel_0.8.2            crayon_1.3.4            
[64] lattice_0.20-41          cowplot_1.0.0            splines_3.6.1           
[67] pillar_1.4.4             igraph_1.2.5             future.apply_1.5.0      
[70] reshape2_1.4.4           codetools_0.2-16         leiden_0.3.3            
[73] glue_1.4.1               lsei_1.2-0               data.table_1.12.8       
[76] png_0.1-7                vctrs_0.3.0              gtable_0.3.0            
[79] RANN_2.6.1               purrr_0.3.4              tidyr_1.1.0             
[82] future_1.17.0            assertthat_0.2.1         rsvd_1.0.3              
[85] survival_3.1-12          viridisLite_0.3.0        tibble_3.0.1            
[88] cluster_2.1.0            globals_0.12.5           fitdistrplus_1.0-14     
[91] ellipsis_0.3.1           ROCR_1.0-7
```  

I reinstalled the newest monocle3, but it did not work.

I do not know what is the matter. Can you give me a help?

**Comment by brgew** [comment] 2020-06-01 23:47
Hi,
I am unable to reproduce the error on two different systems when I use the commands

```
devtools::install_github('cole-trapnell-lab/monocle3', ref="develop")
library(dplyr) # imported for some downstream data manipulation

expression_matrix <- readRDS(url("http://staff.washington.edu/hpliner/data/cao_l2_expression.rds"))
cell_metadata <- readRDS(url("http://staff.washington.edu/hpliner/data/cao_l2_colData.rds"))
gene_annotation <- readRDS(url("http://staff.washington.edu/hpliner/data/cao_l2_rowData.rds"))

cds <- new_cell_data_set(expression_matrix,
                         cell_metadata = cell_metadata,
                         gene_metadata = gene_annotation)
cds <- preprocess_cds(cds, num_dim = 100)
cds <- reduce_dimension(cds)
```

I notice that the error occurs in the uwot::umap code. Could you try reinstalling it? (It seems unlikely that this is the problem but I have no better suggestion.)
Thank you.

**Comment by brgew** [comment] 2020-09-29 22:09
Hi,
I am closing this issue until I receive more information.

**Closed by brgew** 2020-09-29 22:09 UTC
Labels: waiting on info
