### ISSUE TITLE
plot_cells() function bug in color cells by gene expression

### ISSUE THREAD

**Issue by xiechangxiao** [cole-trapnell-lab/monocle3#106] opened 2019-06-13 05:45 UTC
plot_cells() function bug in color cells by gene expression.
When I use plot_cells funtion color cells by gene expression, it cannot give me correct picture.
my code as below:
plot_cells(cds, genes=c("A1BG"),show_trajectory_graph=FALSE, label_cell_groups=FALSE)
but the result as below.
![plot_cell](https://user-images.githubusercontent.com/35715828/59406803-f0e1d200-8de1-11e9-9819-22dd79835ab3.png)

**Comment by hpliner** [comment] 2019-06-13 18:54
Are you certain that the gene is in your CDS? In either the gene_short_name or feature names (row.names of fData)? That's the behavior I get when a gene is missing. In 0.1.1 an error will be thrown

**Comment by xiechangxiao** [comment] 2019-06-14 01:06
Thanks, This gene is in my CDS. I also follow your code in your monocle3 _docs(https://cole-trapnell-lab.github.io/monocle3/monocle3_docs/#constructing-single-cell-trajectories) and I also cannot get a  correct picture.

**Comment by hpliner** [comment] 2019-06-14 16:18
Ok thanks, we'll push a fix in release 0.1.1 which will come out next week

**Comment by hpliner** [comment] 2019-06-18 17:24
Hi @xiechangxiao 
I haven't been able to reproduce your error on my system, but I've pushed some changes that I'm guessing might have been the issue to our develop branch. 

If you have a chance, you can test the new version by running: `devtools::install_github("cole-trapnell-lab/monocle3", ref="develop")` which will install the develop branch and let me know if it fixed the issue. The develop branch will be merged into master at the end of this week.

**Comment by xiechangxiao** [comment] 2019-06-19 05:14
Thanks, I installed monocle3 follow your comment, but it cannot plot it. 
my cds and error as bellow:
![image](https://user-images.githubusercontent.com/35715828/59738474-efa61e80-9293-11e9-9bc8-fee0e24fca03.png)
this gene 'AL627309.1' is in my cds,but this function cannot find it.

**Comment by hpliner** [comment] 2019-06-20 00:16
Thanks for trying this out. It's a very strange bug that we believe has to do with row names sometimes missing... Can you send your current sessionInfo() ? We think it might be a namespace collision and we're narrowing stuff down!

**Comment by xiechangxiao** [comment] 2019-06-20 00:54
My sessionInfo() as below:
![1](https://user-images.githubusercontent.com/35715828/59810659-ee7afd00-9338-11e9-8134-5a65b08f50ee.png)
![2](https://user-images.githubusercontent.com/35715828/59810665-f33fb100-9338-11e9-8edd-d7910cea2bec.png)

**Comment by hpliner** [comment] 2019-06-20 19:22
Ok, we believe we've figured out the issue. Looks like this is a summarizedexperiment bug that was solved in 1.11.5. We've update the requirements in the develop version, but try updating SummarizeExperiment and reloading Monocle3 and see if that fixes it for you.

**Comment by xiechangxiao** [comment] 2019-06-21 03:00
Thanks, it's ok now.

**Comment by hpliner** [comment] 2019-06-24 17:05
Fixed in 0.1.1

**Closed by hpliner** 2019-06-24 17:05 UTC
Labels: fixed in develop
