### ISSUE TITLE
Combined_cds bug

### ISSUE THREAD

**Issue by yasserIRCM** [cole-trapnell-lab/monocle3#252] opened 2019-11-12 21:48 UTC
**Describe the bug**
Hi there is a probleme with the Combine_cds function.
I have noticed there was a double comma on line 689
fd <- fd[intersect(row.names(fd), gene_list),, drop=FALSE]   
as you can see there was a typo.
I corrected but it is still reporting an error.

**To Reproduce**
> ## combining CDS objects
> E124 <- combine_cds(ist(E125,E115,E105),keep_all_genes = FALSE, cell_names_unique = FALSE)
> ## Error in if (any(as.logical(i))) { : 
> ##  missing value where TRUE/FALSE needed 

**traceback()**
traceback()
4: .M.vectorSub(x, i)
3: exp[intersect(row.names(exp), gene_list), drop = FALSE]
2: exp[intersect(row.names(exp), gene_list), drop = FALSE] at #67   ( the 67 here correspond to 689, I get #67 because I have run the function from the source)
1: combine_cds(E124, keep_all_genes = FALSE, cell_names_unique = FALSE)

**Expected behavior**
Combined objects

**Comment by hpliner** [comment] 2019-11-14 12:42
Can you please post your sessionInfo ?

**Comment by yasserIRCM** [comment] 2019-11-14 15:34
Hi, here is the session info.

R version 3.6.1 (2019-07-05)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS/LAPACK: /home/yasser/miniconda2/envs/Monocle/lib/R/lib/libRblas.so

locale:
[1] en_US.UTF-8

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] udunits2_0.13               future_1.14.0               ggExtra_0.9                 tidyr_0.8.3                
 [5] gridExtra_2.3               stringr_1.4.0               magrittr_1.5                tibble_2.1.1               
 [9] gginnards_0.0.2             ggplot2_3.2.1               dplyr_0.8.0.1               Seurat_3.1.1               
[13] monocle3_0.2.1.2            SingleCellExperiment_1.6.0  SummarizedExperiment_1.14.1 DelayedArray_0.10.0        
[17] BiocParallel_1.18.1         matrixStats_0.55.0          GenomicRanges_1.36.1        GenomeInfoDb_1.20.0        
[21] IRanges_2.18.3              S4Vectors_0.22.1            Biobase_2.44.0              BiocGenerics_0.30.0        

loaded via a namespace (and not attached):
 [1] Rtsne_0.15             colorspace_1.4-1       ggridges_0.5.1         XVector_0.24.0         rstudioapi_0.10       
 [6] leiden_0.3.1           listenv_0.7.0          npsurv_0.4-0           ggrepel_0.8.1          codetools_0.2-16      
[11] splines_3.6.1          R.methodsS3_1.7.1      lsei_1.2-0             jsonlite_1.6           ica_1.0-2             
[16] cluster_2.1.0          png_0.1-7              R.oo_1.23.0            uwot_0.1.4             shiny_1.3.2           
[21] sctransform_0.2.0      compiler_3.6.1         httr_1.4.0             assertthat_0.2.1       Matrix_1.2-17         
[26] lazyeval_0.2.2         later_0.8.0            htmltools_0.3.6        tools_3.6.1            rsvd_1.0.2            
[31] igraph_1.2.4.1         gtable_0.3.0           glue_1.3.1             GenomeInfoDbData_1.2.1 RANN_2.6.1            
[36] reshape2_1.4.3         Rcpp_1.0.2             gdata_2.18.0           ape_5.3                nlme_3.1-141          
[41] gbRd_0.4-11            lmtest_0.9-37          globals_0.12.4         mime_0.6               miniUI_0.1.1.1        
[46] irlba_2.3.3            gtools_3.8.1           zlibbioc_1.30.0        MASS_7.3-51.4          zoo_1.8-6             
[51] scales_1.0.0           promises_1.0.1         RColorBrewer_1.1-2     yaml_2.2.0             reticulate_1.13       
[56] pbapply_1.4-2          stringi_1.4.3          caTools_1.17.1.2       bibtex_0.4.2           Rdpack_0.11-0         
[61] SDMTools_1.1-221.1     rlang_0.4.1            pkgconfig_2.0.2        bitops_1.0-6           lattice_0.20-38       
[66] ROCR_1.0-7             purrr_0.3.2            htmlwidgets_1.3        labeling_0.3           cowplot_1.0.0         
[71] tidyselect_0.2.5       RcppAnnoy_0.0.13       plyr_1.8.4             R6_2.4.0               gplots_3.0.1.1        
[76] pillar_1.3.1           withr_2.1.2            fitdistrplus_1.0-14    survival_3.1-7         RCurl_1.95-4.12       
[81] future.apply_1.3.0     tsne_0.1-3             crayon_1.3.4           KernSmooth_2.23-16     plotly_4.9.0          
[86] viridis_0.5.1          grid_3.6.1             data.table_1.12.6      metap_1.1              digest_0.6.18         
[91] xtable_1.8-4           httpuv_1.5.1           R.utils_2.9.0          RcppParallel_4.4.4     munsell_0.5.0         
[96] viridisLite_0.3.0

**Comment by yasserIRCM** [comment] 2019-11-14 15:37
by the way. this happened using the Develop Branch.

**Comment by hpliner** [comment] 2019-11-18 16:02
Hi,
So the double comma you point to is not a typo, it refers to including all columns - i.e. the first argument when subsetting is rows, second is columns, then drop =F is added as a third. From the traceback you provided, it looks like you removed the second comma, which would change the output. Can you change it back and post the traceback?

**Comment by yasserIRCM** [comment] 2019-11-18 16:21
Hi there , 
here is output. (it gives me a error I had already mentionned in a separate issue, which is still not solved, no metter what branch I use)

> E123=list(E125,E115,E105)
> E123 <- combine_cds(E123,keep_all_genes = FALSE, cell_names_unique = FALSE)
> Error in [<-.data.frame(*tmp*, , n, value = NA) 
> missing values are not allowed in subscripted assignments of data frames

is there anyway around using this function? is there a way I could merge my datasets using Seurat then convert the seurat Object into a Monocle3 object?

please let me know.

**Comment by hpliner** [comment] 2019-11-18 16:42
Ok, I can reproduce this bug when a column name of one of the pData tables in your three input cds' is NA. Can you check/post the names of your columns in your pData table?
names(pData(E125)) # etc

**Comment by yasserIRCM** [comment] 2019-11-18 19:49
Hi again. 
sorry had to reinstall everything to rerun this.
(I have 3 data sets I want to merge)
E125 <- load_cellranger_data("/home/yasser/Downloads/E12_5")
E115 <- load_cellranger_data("/home/yasser/Downloads/E11_5")
E105 <- load_cellranger_data("/home/yasser/Downloads/E10_5")
E123=list(E125,E115,E105)
names(pData(E125))        
names(pData(E115))        
names(pData(E105))        

> names(pData(E125))
[1] "barcode"     "Size_Factor"
> names(pData(E125))        
[1] "barcode"     "Size_Factor"
>         names(pData(E115))        
[1] "barcode"     "Size_Factor"
>         names(pData(E105))
[1] "barcode"     "Size_Factor"

**Comment by yasserIRCM** [comment] 2019-11-18 22:43
Hi there.
I solved by exporting my merged Seurat object using Write10X (from @daskelly earlycross package) then reimported using the normal , load_cellranger_data then added my metadata to the object.

for the time being, this is my only solution

**Comment by kathirij** [comment] 2020-02-22 23:17
I think I am getting a similar issue here... 

> cds1 <- load_cellranger_data("/media/chapmanlab/Seagate Expansion Drive1/HTII280pos_Organoids/Monocle/d0")


> all_cds <- combine_cds(list(cds1, cds2, cds3, cds4))
Error: One of the input CDS' has a colData column name that is NA, please remove or rename that column before proceeding.

My colData of all of the cds look like this...

> colData(cds1)
DataFrame with 8526 rows and 2 columns
                              barcode       Size_Factor
                             <factor>         <numeric>
AAACCTGAGACTACAA-1 AAACCTGAGACTACAA-1   0.4400243670728
AAACCTGAGAGTGACC-1 AAACCTGAGAGTGACC-1 0.604913373267631
AAACCTGAGCACCGTC-1 AAACCTGAGCACCGTC-1 0.961738125224639
AAACCTGAGCCCGAAA-1 AAACCTGAGCCCGAAA-1  1.08461544457882
AAACCTGAGGTAGCCA-1 AAACCTGAGGTAGCCA-1 0.517869551512825
...                               ...               ...
TTTGTCAGTATAGTAG-1 TTTGTCAGTATAGTAG-1 0.658045800742568
TTTGTCAGTTAAGATG-1 TTTGTCAGTTAAGATG-1 0.554664100771954
TTTGTCATCCGTAGGC-1 TTTGTCATCCGTAGGC-1  1.16603024946936
TTTGTCATCGGGAGTA-1 TTTGTCATCGGGAGTA-1 0.653377835538052
TTTGTCATCTTGTACT-1 TTTGTCATCTTGTACT-1  1.85277030691028'

The names of the columns/rows is as below (true for all four cds's).

> names(pData(cds1))
[1] "barcode"     "Size_Factor"'
names(rowData(cds_d0))
[1] "id"              "gene_short_name"


I am using monocle3_0.2.1.4 version (installed using the development branch).

**Comment by kathirij** [comment] 2020-02-22 23:21
I think I am getting a similar issue here... 

> cds1 <- load_cellranger_data("/d0")
cds 2 <- load_cellranger_data("/d7")
cds3 <- load_cellranger_data("/d14")
cds4 <- load_cellranger_data("/d21")

> all_cds <- combine_cds(list(cds1, cds2, cds3, cds4))
Error: One of the input CDS' has a colData column name that is NA, please remove or rename that column before proceeding.

My colData of all of the cds look like this...

> colData(cds1)
DataFrame with 8526 rows and 2 columns
                              barcode       Size_Factor
                             <factor>         <numeric>
AAACCTGAGACTACAA-1 AAACCTGAGACTACAA-1   0.4400243670728
AAACCTGAGAGTGACC-1 AAACCTGAGAGTGACC-1 0.604913373267631
AAACCTGAGCACCGTC-1 AAACCTGAGCACCGTC-1 0.961738125224639
AAACCTGAGCCCGAAA-1 AAACCTGAGCCCGAAA-1  1.08461544457882
AAACCTGAGGTAGCCA-1 AAACCTGAGGTAGCCA-1 0.517869551512825
...                               ...               ...
TTTGTCAGTATAGTAG-1 TTTGTCAGTATAGTAG-1 0.658045800742568
TTTGTCAGTTAAGATG-1 TTTGTCAGTTAAGATG-1 0.554664100771954
TTTGTCATCCGTAGGC-1 TTTGTCATCCGTAGGC-1  1.16603024946936
TTTGTCATCGGGAGTA-1 TTTGTCATCGGGAGTA-1 0.653377835538052
TTTGTCATCTTGTACT-1 TTTGTCATCTTGTACT-1  1.85277030691028'

The names of the columns/rows is as below (true for all four cds's).

> names(pData(cds1))
[1] "barcode"     "Size_Factor"'
names(rowData(cds1))
[1] "id"              "gene_short_name"


I am using monocle3_0.2.1.4 version (installed using the development branch).

**Comment by hpliner** [comment] 2020-02-25 12:29
Hi @kathirij, Thanks for the report. Can you please post your sessionInfo() and also post the result of running: 
```
cds_list <- list(cds1, cds2, cds3, cds4)
sapply(cds_list, function(cds)
    sum(is.na(names(colData(cds)))) != 0)
```

**Comment by kathirij** [comment] 2020-02-26 19:23
Hi hpliner,
Thanks for the response and sorry for the delay in getting back. (Travelling back from a conference). But here is the information.


> sapply(cds_list, function(cds)
> sum(is.na(names(colData(cds)))) != 0)
> [1] FALSE FALSE FALSE FALSE



```
sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] dplyr_0.8.4                 ggplot2_3.2.1              
 [3] Matrix_1.2-18               monocle3_0.2.1.4           
 [5] SingleCellExperiment_1.6.0  SummarizedExperiment_1.14.1
 [7] DelayedArray_0.10.0         BiocParallel_1.18.1        
 [9] matrixStats_0.55.0          GenomicRanges_1.36.1       
[11] GenomeInfoDb_1.20.0         IRanges_2.18.3             
[13] S4Vectors_0.22.1            Biobase_2.44.0             
[15] BiocGenerics_0.30.0        

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3             plyr_1.8.5             compiler_3.6.2        
 [4] pillar_1.4.3           XVector_0.24.0         viridis_0.5.1         
 [7] bitops_1.0-6           tools_3.6.2            zlibbioc_1.30.0       
[10] viridisLite_0.3.0      lifecycle_0.1.0        tibble_2.1.3          
[13] gtable_0.3.0           lattice_0.20-38        pkgconfig_2.0.3       
[16] rlang_0.4.4            rstudioapi_0.11        gridExtra_2.3         
[19] GenomeInfoDbData_1.2.1 withr_2.1.2            stringr_1.4.0         
[22] tidyselect_1.0.0       grid_3.6.2             glue_1.3.1            
[25] R6_2.4.1               reshape2_1.4.3         purrr_0.3.3           
[28] magrittr_1.5           scales_1.1.0           assertthat_0.2.1      
[31] colorspace_1.4-1       stringi_1.4.6          RCurl_1.98-1.1        
[34] lazyeval_0.2.2         munsell_0.5.0          crayon_1.3.4      
```

**Comment by kathirij** [comment] 2020-03-02 06:54
I am still having this issue.. any thoughts?

**Comment by hpliner** [comment] 2020-03-05 14:52
Hi @kathirij,
Ok, I think I've found the beginning of the issue. Looks like I had a typo in my error message that printed that there were NAs in the colData when there were actually NAs in the rowData. Can your run the same test above, with your CDS' but looking at the rowData?
```
any(sapply(cds_list, function(cds)
    sum(is.na(names(rowData(cds)))) != 0))
```

**Comment by kathirij** [comment] 2020-03-05 20:22
You're correct... I have some rowData names that are NA... here's the output.

> cds_list <- list(cds_d0, cds_d7, cds_d14, cds_d21)
> any(sapply(cds_list, function(cds)
> +   sum(is.na(names(rowData(cds)))) != 0))
> [1] TRUE


Looking specifically, only two of them datasets have the header as "NA" (for the gene expression column).. both of which were run with the latest cellranger.. whereas other two datasets are over a year older and therefore don't have that column. (somehow i missed this when I ran names(rowData(cds)) earlier on individual cds objects. Sorry!).

Should I just remove that column so that rowData of all the datasets have exactly two columns? If so, could you suggest what should be the code? (rather a noob question).

Thanks!

**Comment by hpliner** [comment] 2020-03-09 13:24
Hi @kathirij , Glad that fixed things. You can deal with this either way - you can either remove the columns with something like `rowData(cds1) <- rowData(cds1)[,c(1,2,4)]` - if column 3 was the problem for example (and you had 4 columns overall), or you can rename the columns using `names(rowData(cds1))[3] <- "new_name"` (again if column 3 is the problem) and then leave them. If there are columns in one of the rowData tables and not the others then the genes that don't have that information will be filled in with NA

Hopefully this answers your question! I'm going to close the issue, reply/reopen if you have further problems.

**Closed by hpliner** 2020-03-09 13:24 UTC
Labels: bug

**Comment by kathirij** [comment] 2020-03-10 04:55
Thanks so much for your help!
