### ISSUE TITLE
Error loading monocle3

### ISSUE THREAD

**Issue by rdona17** [cole-trapnell-lab/monocle3#304] opened 2020-03-19 01:44 UTC
Error loading Monocle3 while following directions on website http://cole-trapnell-lab.github.io/monocle-release/monocle3/ 

**To Reproduce**
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install()
BiocManager::install(c('BiocGenerics', 'DelayedArray', 'DelayedMatrixStats',
                       'limma', 'S4Vectors', 'SingleCellExperiment',
                       'SummarizedExperiment', 'batchelor'))
install.packages("devtools")
devtools::install_github('cole-trapnell-lab/leidenbase')
#this didn't seem to work...
devtools::install_github('cole-trapnell-lab/monocle3')

**traceback()**
After the error, run traceback() in R and post the output:
8: stop(remote_install_error(remotes[[i]], e))
7: value[[3L]](cond)
6: tryCatchOne(expr, names, parentenv, handlers[[1L]])
5: tryCatchList(expr, classes, parentenv, handlers)
4: tryCatch(res[[i]] <- install_remote(remotes[[i]], ...), error = function(e) {
       stop(remote_install_error(remotes[[i]], e))
   })
3: install_remotes(remotes, auth_token = auth_token, host = host, 
       dependencies = dependencies, upgrade = upgrade, force = force, 
       quiet = quiet, build = build, build_opts = build_opts, build_manual = build_manual, 
       build_vignettes = build_vignettes, repos = repos, type = type, 
       ...)
2: pkgbuild::with_build_tools({
       ellipsis::check_dots_used(action = getOption("devtools.ellipsis_action", 
           rlang::warn))
       {
           remotes <- lapply(repo, github_remote, ref = ref, subdir = subdir, 
               auth_token = auth_token, host = host)
           install_remotes(remotes, auth_token = auth_token, host = host, 
               dependencies = dependencies, upgrade = upgrade, force = force, 
               quiet = quiet, build = build, build_opts = build_opts, 
               build_manual = build_manual, build_vignettes = build_vignettes, 
               repos = repos, type = type, ...)
       }
   }, required = FALSE)
1: devtools::install_github("cole-trapnell-lab/monocle3")

**sessionInfo():**
Run sessionInfo() in R and post the output
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.3

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.14

loaded via a namespace (and not attached):
  [1] Seurat_3.1.4        TH.data_1.0-10      Rtsne_0.15          colorspace_1.4-1   
  [5] ellipsis_0.3.0      ggridges_0.5.2      rprojroot_1.3-2     fs_1.3.2           
  [9] rstudioapi_0.11     leiden_0.3.3        listenv_0.8.0       npsurv_0.4-0       
 [13] remotes_2.1.1       ggrepel_0.8.2       fansi_0.4.1         mvtnorm_1.1-0      
 [17] codetools_0.2-16    splines_3.6.1       mnormt_1.5-6        lsei_1.2-0         
 [21] TFisher_0.2.0       pkgload_1.0.2       jsonlite_1.6.1      ica_1.0-2          
 [25] cluster_2.1.0       png_0.1-7           uwot_0.1.8          sctransform_0.2.1  
 [29] BiocManager_1.30.10 compiler_3.6.1      httr_1.4.1          backports_1.1.5    
 [33] assertthat_0.2.1    Matrix_1.2-18       lazyeval_0.2.2      cli_2.0.2          
 [37] htmltools_0.4.0     prettyunits_1.1.1   tools_3.6.1         rsvd_1.0.3         
 [41] igraph_1.2.4.2      gtable_0.3.0        glue_1.3.2          RANN_2.6.1         
 [45] reshape2_1.4.3      dplyr_0.8.5         Rcpp_1.0.4          Biobase_2.46.0     
 [49] vctrs_0.2.4         multtest_2.42.0     gdata_2.18.0        ape_5.3            
 [53] nlme_3.1-145        gbRd_0.4-11         lmtest_0.9-37       stringr_1.4.0      
 [57] globals_0.12.5      ps_1.3.2            testthat_2.3.2      lifecycle_0.2.0    
 [61] irlba_2.3.3         gtools_3.8.1        devtools_2.2.2      future_1.16.0      
 [65] MASS_7.3-51.5       zoo_1.8-7           scales_1.1.0        parallel_3.6.1     
 [69] sandwich_2.5-1      RColorBrewer_1.1-2  curl_4.3            memoise_1.1.0      
 [73] pbapply_1.4-2       gridExtra_2.3       ggplot2_3.3.0       stringi_1.4.6      
 [77] desc_1.2.0          mutoss_0.1-12       plotrix_3.7-7       caTools_1.18.0     
 [81] BiocGenerics_0.32.0 pkgbuild_1.0.6      bibtex_0.4.2.2      Rdpack_0.11-1      
 [85] rlang_0.4.5         pkgconfig_2.0.3     bitops_1.0-6        lattice_0.20-40    
 [89] ROCR_1.0-7          purrr_0.3.3         patchwork_1.0.0     htmlwidgets_1.5.1  
 [93] cowplot_1.0.0       tidyselect_1.0.0    processx_3.4.2      RcppAnnoy_0.0.16   
 [97] plyr_1.8.6          magrittr_1.5        R6_2.4.1            gplots_3.0.3       
[101] multcomp_1.4-12     withr_2.1.2         pillar_1.4.3        sn_1.5-5           
[105] fitdistrplus_1.0-14 survival_3.1-11     tibble_2.1.3        future.apply_1.4.0 
[109] tsne_0.1-3          crayon_1.3.4        KernSmooth_2.23-16  plotly_4.9.2       
[113] usethis_1.5.1       grid_3.6.1          data.table_1.12.8   callr_3.4.2        
[117] metap_1.3           digest_0.6.25       tidyr_1.0.2         numDeriv_2016.8-1.1
[121] stats4_3.6.1        munsell_0.5.0       viridisLite_0.3.0   sessioninfo_1.1.1  

Thank you!

**Comment by iwilliams91** [comment] 2020-03-28 15:32
I had the same issue. There seems to be a compiler selection issue after updating to catalina... following the steps below resolved the issue for me.

[https://github.com/cole-trapnell-lab/leidenbase/issues/8#issuecomment-556930423](url)

**Comment by hpliner** [comment] 2020-05-13 14:28
Is this solved?

**Comment by stwigg** [comment] 2020-05-14 08:59
I have the same issue as rdona17 when trying to load Monocle3:

Error: package or namespace load failed for ‘leidenbase’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-leidenbase/00new/leidenbase/libs/leidenbase.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-leidenbase/00new/leidenbase/libs/leidenbase.so, 6): Library not loaded: @rpath/libicui18n.58.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/00LOCK-leidenbase/00new/leidenbase/libs/leidenbase.so
  Reason: image not found
Error: loading failed
Execution halted
ERROR: loading failed

> traceback()
8: stop(remote_install_error(remotes[[i]], e))
7: value[[3L]](cond)
6: tryCatchOne(expr, names, parentenv, handlers[[1L]])
5: tryCatchList(expr, classes, parentenv, handlers)
4: tryCatch(res[[i]] <- install_remote(remotes[[i]], ...), error = function(e) {
       stop(remote_install_error(remotes[[i]], e))
   })
3: install_remotes(remotes, auth_token = auth_token, host = host, 
       dependencies = dependencies, upgrade = upgrade, force = force, 
       quiet = quiet, build = build, build_opts = build_opts, build_manual = build_manual, 
       build_vignettes = build_vignettes, repos = repos, type = type, 
       ...)
2: pkgbuild::with_build_tools({
       ellipsis::check_dots_used(action = getOption("devtools.ellipsis_action", 
           rlang::warn))
       {
           remotes <- lapply(repo, github_remote, ref = ref, subdir = subdir, 
               auth_token = auth_token, host = host)
           install_remotes(remotes, auth_token = auth_token, host = host, 
               dependencies = dependencies, upgrade = upgrade, force = force, 
               quiet = quiet, build = build, build_opts = build_opts, 
               build_manual = build_manual, build_vignettes = build_vignettes, 
               repos = repos, type = type, ...)
       }
   }, required = FALSE)
1: devtools::install_github("cole-trapnell-lab/leidenbase")

> sessionInfo()
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.4

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] reticulate_1.15 Seurat_3.1.5   

loaded via a namespace (and not attached):
  [1] nlme_3.1-147        tsne_0.1-3          fs_1.4.1            usethis_1.6.1      
  [5] devtools_2.3.0      RcppAnnoy_0.0.16    RColorBrewer_1.1-2  httr_1.4.1         
  [9] rprojroot_1.3-2     backports_1.1.7     sctransform_0.2.1   tools_4.0.0        
 [13] R6_2.4.1            irlba_2.3.3         KernSmooth_2.23-17  uwot_0.1.8         
 [17] lazyeval_0.2.2      colorspace_1.4-1    npsurv_0.4-0.1      withr_2.2.0        
 [21] tidyselect_1.1.0    gridExtra_2.3       prettyunits_1.1.1   processx_3.4.2     
 [25] curl_4.3            compiler_4.0.0      cli_2.0.2           desc_1.2.0         
 [29] plotly_4.9.2.1      scales_1.1.1        lmtest_0.9-37       ggridges_0.5.2     
 [33] callr_3.4.3         pbapply_1.4-2       stringr_1.4.0       digest_0.6.25      
 [37] pkgconfig_2.0.3     htmltools_0.4.0     sessioninfo_1.1.1   htmlwidgets_1.5.1  
 [41] rlang_0.4.6         rstudioapi_0.11     zoo_1.8-8           jsonlite_1.6.1     
 [45] ica_1.0-2           dplyr_0.8.5         magrittr_1.5        patchwork_1.0.0    
 [49] Matrix_1.2-18       Rcpp_1.0.4.6        munsell_0.5.0       fansi_0.4.1        
 [53] ape_5.3             lifecycle_0.2.0     stringi_1.4.6       MASS_7.3-51.6      
 [57] pkgbuild_1.0.8      Rtsne_0.15          plyr_1.8.6          grid_4.0.0         
 [61] parallel_4.0.0      listenv_0.8.0       ggrepel_0.8.2       crayon_1.3.4       
 [65] lattice_0.20-41     cowplot_1.0.0       splines_4.0.0       ps_1.3.3           
 [69] pillar_1.4.4        igraph_1.2.5        future.apply_1.5.0  reshape2_1.4.4     
 [73] codetools_0.2-16    pkgload_1.0.2       leiden_0.3.3        glue_1.4.1         
 [77] lsei_1.2-0.1        remotes_2.1.1       data.table_1.12.8   BiocManager_1.30.10
 [81] png_0.1-7           vctrs_0.3.0         testthat_2.3.2      gtable_0.3.0       
 [85] RANN_2.6.1          purrr_0.3.4         tidyr_1.0.3         future_1.17.0      
 [89] assertthat_0.2.1    ggplot2_3.3.0       rsvd_1.0.3          survival_3.1-12    
 [93] viridisLite_0.3.0   tibble_3.0.1        memoise_1.1.0       cluster_2.1.0      
 [97] globals_0.12.5      fitdistrplus_1.0-14 ellipsis_0.3.0      ROCR_1.0-11      

Any help would be greatly appreciated!

**Comment by lianov** [comment] 2020-06-18 01:51
Can confirm that I am getting the same error as the OP (minor difference in R version - 3.6.2). Is it possible that this is linked to macOS Catalina since me, @rdona17  and @stwigg all have this OS version?

```
sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.5

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] rstudioapi_0.11     magrittr_1.5        usethis_1.6.1       devtools_2.3.0      pkgload_1.1.0       R6_2.4.1            rlang_0.4.6        
 [8] fansi_0.4.1         tools_3.6.2         pkgbuild_1.0.8      sessioninfo_1.1.1   cli_2.0.2           withr_2.2.0         ellipsis_0.3.1     
[15] remotes_2.1.1       assertthat_0.2.1    digest_0.6.25       rprojroot_1.3-2     crayon_1.3.4        processx_3.4.2      BiocManager_1.30.10
[22] callr_3.4.3         fs_1.4.1            ps_1.3.3            curl_4.3            testthat_2.3.2      memoise_1.1.0       glue_1.4.1         
[29] compiler_3.6.2      desc_1.2.0          backports_1.1.8     prettyunits_1.1.1  
```

**Comment by brgew** [comment] 2020-07-08 18:54
Hi,
I don't know the reasons for these failures...it looks like there may be more than one. I tried reproducing the error by installing R, gfortran, and Monocle3 on a Mac running Catalina but the install is successful. A difference is that I installed R 4.0.2, which I downloaded from https://ftp.osuosl.org/pub/cran/bin/macosx/R-4.0.2.pkg. I installed gfortran 8.2 from the www site https://github.com/fxcoudert/gfortran-for-macOS/releases (needed to build leidenbase). Can you try re-installing using R 4.0.2?

**Comment by brgew** [comment] 2020-11-23 22:01
Hi,
I am closing this issue in the absence of additional information.

**Closed by brgew** 2020-11-23 22:01 UTC
Labels: bug, waiting on info
