### ISSUE TITLE
Error when running learn_graph

### ISSUE THREAD

**Issue by andrewhill157** [cole-trapnell-lab/monocle3#102] opened 2019-06-12 21:39 UTC
When running learn graph:
```
cds = preprocess_cds(cds, method='LSI', num_dim = 50)
cds = reduce_dimension(cds, preprocess_method='LSI', reduction_method='UMAP')
cds = cluster_cells(cds, reduction_method='UMAP')
cds = learn_graph(cds)
```

I get the following error:
```
Error in t(reducedDims(cds)[[reduction_method]])[, data_df[, "source"]] :
 subscript out of bounds
```

Get the same error even when not specifying LSI (all other params the same).

The CDS just prior to calling learn_graph (in this case the version without specifying LSI) is saved here:
```
/net/shendure/vol10/projects/silvia/temp/cds.RDS
```

Potential clue seems to be that at least when running this line in debug mode:
https://github.com/cole-trapnell-lab/monocle3/blob/c00877ed620c3e50fb723303bcd4e003905a43ba/R/learn_graph.R#L690

The `data_df` variable has a `source` column but the values do not correspond to cell IDs so (they are `Y_#`), which means that the subsetting of the transposed UMAP coordinates runs into an invalid indexing error. I am not very familiar with the functions involved here, so not sure why this would happen.
```
Browse[3]> head(data_df)
                                               P_1        P_2 source target
GGAGTCCATTGGAGAATGGCGTATCAATATCCGAGAGAGG  1.9934887  0.7234073    Y_1   Y_46
TCATAGGCTTTTGATGCCTCAGTAGATCTAGCGACCAGTT  1.8347589  1.2237542  Y_145  Y_313
GGATATACGGCGATATATCTTCTTAATCAGCGGTCTCATA  3.9525610  1.8215328  Y_334  Y_368
AGCTAATATTGAATTCTCCATCTAGTTCCACATTAACGGA  3.9525610  1.8215328  Y_334  Y_368
GTTATTAATTGGCGTCTGCCGTATACGTAACATTAACGGA  3.1983778  2.3517972  Y_157  Y_185
AAGTCTTCTGTCGGAGTATGGTTCCGTATCTGGACCTTAG -0.9880947 -1.3047595  Y_211    Y_3
```

Not sure if really relevant for this question but here is sessionInfo:
```
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.9 (Final)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblaso-r0.3.3.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats4    parallel  stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] Matrix_1.2-15               stringr_1.4.0              
 [3] monocle3_0.0.0.9004         SingleCellExperiment_1.4.1 
 [5] SummarizedExperiment_1.12.0 DelayedArray_0.8.0         
 [7] BiocParallel_1.16.6         matrixStats_0.54.0         
 [9] GenomicRanges_1.34.0        GenomeInfoDb_1.18.2        
[11] IRanges_2.16.0              S4Vectors_0.20.1           
[13] Biobase_2.42.0              BiocGenerics_0.28.0        

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1             RSpectra_0.13-1        compiler_3.5.2        
 [4] pillar_1.4.1           plyr_1.8.4             XVector_0.22.0        
 [7] viridis_0.5.1          bitops_1.0-6           tools_3.5.2           
[10] zlibbioc_1.28.0        uwot_0.1.3             viridisLite_0.3.0     
[13] tibble_2.1.3           gtable_0.3.0           lattice_0.20-38       
[16] pkgconfig_2.0.2        rlang_0.3.4            igraph_1.2.4.1        
[19] ggrepel_0.8.1          gridExtra_2.3          GenomeInfoDbData_1.2.0
[22] dplyr_0.8.1            grid_3.5.2             tidyselect_0.2.5      
[25] glue_1.3.1             R6_2.4.0               RcppAnnoy_0.0.12      
[28] RANN_2.6.1             irlba_2.3.3            reshape2_1.4.3        
[31] purrr_0.3.2            ggplot2_3.1.1          magrittr_1.5          
[34] codetools_0.2-16       scales_1.0.0           assertthat_0.2.1      
[37] colorspace_1.4-1       labeling_0.3           proxy_0.4-23          
[40] stringi_1.4.3          RcppParallel_4.4.2-2   RCurl_1.95-4.11       
[43] lazyeval_0.2.2         munsell_0.5.0          crayon_1.3.4  
```

**Comment by hpliner** [comment] 2019-06-12 23:08
@andrewhill157 I couldn't reproduce the error...can you try pulling the latest and trying again?

**Comment by andrewhill157** [comment] 2019-06-12 23:47
Cool, thanks for trying -- I mentioned to Silvia (she was one who saw ran into this) and she said could try reinstalling, probably sometime tomorrow I think

**Comment by andrewhill157** [comment] 2019-06-13 23:48
Ok, I think Silvia and I figured out when the bug occurs.

If you run this is should reproduce the error:
```
options(stringsAsFactors = FALSE)
cds = readRDS('/net/shendure/vol10/projects/silvia/temp/cds.RDS')
cds=learn_graph(cds)
```

Factors are the worst...

**Comment by hpliner** [comment] 2019-06-18 18:35
This was a nice find. Factors being terrible and letting a copy-paste error stand. Fixed in develop!

**Comment by hpliner** [comment] 2019-06-24 17:06
Fixed in 0.1.1

**Closed by hpliner** 2019-06-24 17:06 UTC
Labels: fixed in develop

**Comment by YiweiNiu** [comment] 2021-04-14 14:53
Hi,

Sorry to open a closed issue. But I got this error in monocle3 version 1.0.0.

The command I used

```r
srat.par_2 <- subset(as.Seurat(cds), monocle3_partitions == 2)
cds.par_2 <- as.cell_data_set(srat.par_2)
cds.par_2 <- learn_graph(cds.par_2, verbose = FALSE)
```

And the error message and traceback.

```
|============================================================================================| 100%
Error in dp_mst_list[[as.numeric(cur_partition)]] : subscript out of bounds

5. "igraph" %in% class(graph)
4. is_igraph(graph)
3. igraph::V(dp_mst_list[[as.numeric(cur_partition)]])
2. project2MST(cds, project_point_to_line_segment, orthogonal_proj_tip, verbose, reduction_method, rge_res_Y)
1. learn_graph(cds.par_2, verbose = FALSE)
```

I wonder how this error happened and how to solve this.

Thanks in advance.

**Comment by IStevant** [comment] 2021-05-03 11:06
Hi, 
same error as @YiweiNiu. I used a Seurat object as input, then I subset a partition, and I run learn_graph, just like @YiweiNiu and I have the same error.
I don't have any error while applying learn_graph on the full dataset.

**Comment by fereshtehvosta** [comment] 2021-07-16 08:26
Hi,
same error as @YiweiNiu and @IStevant . when  I subset a Seurat object based on a partition, and I run learn_graph, I get the same error.
I need your help.

**Comment by nkutbw** [comment] 2021-08-24 16:30
Hi,
same error as @YiweiNiu, @IStevant and @fereshtehvosta . when I subset a Seurat object based on a partition, and I run learn_graph, I get the same error.
I need your help, plz :)

**Comment by SimoniMD** [comment] 2021-11-06 22:31
I am also getting this same error as @YiweiNiu, similarly as above, after partitioning an object. Any one with ideas?

**Comment by nkutbw** [comment] 2021-11-07 02:32
> I am also getting this same error as @YiweiNiu, similarly as above, after partitioning an object. Any one with ideas?

I go down r version 4.1.0 to 3.6.3, with the consist monocle and Seurat and then it works.

**Comment by SimoniMD** [comment] 2021-11-12 15:24
i'm unable to go down in R versions and still run Monocle. Any other suggestions?

**Comment by ieiwk** [comment] 2022-01-20 05:58
> Hi, same error as @YiweiNiu. I used a Seurat object as input, then I subset a partition, and I run learn_graph, just like @YiweiNiu and I have the same error. I don't have any error while applying learn_graph on the full dataset.

I think I found the bug, and I immediately tried to fix it. The bug is from monocle3:::project2MST, around 

```
    if (length(dp_mst_list) == 1 & length(unique(partitions)) >
        1) {
        partitions[partitions != "1"] <- "1"
    }
```

The fix is like this:

```
    if (length(dp_mst_list) == 1 && max( as.integer( levels( partitions))) >
        1) {
      levels( partitions)[ as.numeric( levels( partitions)) != '1'] <- '1'
    }
```

Then one also needs to source the code for SeuratWrappers::learn_graph as learn_graph to let learn_graph use the fixed project2MST.
```
learn_graph <- function (cds, use_partition = TRUE, close_loop = TRUE, learn_graph_control = NULL, verbose = FALSE) {
  reduction_method <- "UMAP"
  if (!is.null(learn_graph_control)) {
    assertthat::assert_that(methods::is(learn_graph_control,
                                        "list"))
    assertthat::assert_that(all(names(learn_graph_control) %in%
                                c("euclidean_distance_ratio", "geodesic_distance_ratio",
                                  "minimal_branch_len", "orthogonal_proj_tip",
                                  "prune_graph", "scale", "ncenter", "rann.k",
                                  "maxiter", "eps", "L1.gamma", "L1.sigma")), msg = "Unknown variable in learn_graph_control")
  }
  euclidean_distance_ratio <- ifelse(is.null(learn_graph_control$euclidean_distance_ratio),
                                     1, learn_graph_control$euclidean_distance_ratio)
  geodesic_distance_ratio <- ifelse(is.null(learn_graph_control$geodesic_distance_ratio),
                                    1/3, learn_graph_control$geodesic_distance_ratio)
  minimal_branch_len <- ifelse(is.null(learn_graph_control$minimal_branch_len),
                               10, learn_graph_control$minimal_branch_len)
  orthogonal_proj_tip <- ifelse(is.null(learn_graph_control$orthogonal_proj_tip),
                                FALSE, learn_graph_control$orthogonal_proj_tip)
  prune_graph <- ifelse(is.null(learn_graph_control$prune_graph),
                        TRUE, learn_graph_control$prune_graph)
  ncenter <- learn_graph_control$ncenter
  scale <- ifelse(is.null(learn_graph_control$scale), FALSE,
                  learn_graph_control$scale)
  rann.k <- ifelse(is.null(learn_graph_control$rann.k), 25,
                   learn_graph_control$rann.k)
  maxiter <- ifelse(is.null(learn_graph_control$maxiter), 10,
                    learn_graph_control$maxiter)
  eps <- ifelse(is.null(learn_graph_control$eps), 1e-05, learn_graph_control$eps)
  L1.gamma <- ifelse(is.null(learn_graph_control$L1.gamma),
                     0.5, learn_graph_control$L1.gamma)
  L1.sigma <- ifelse(is.null(learn_graph_control$L1.sigma),
                     0.01, learn_graph_control$L1.sigma)
  assertthat::assert_that(methods::is(cds, "cell_data_set"))
  assertthat::assert_that(reduction_method %in% c("UMAP"),
                          msg = paste0("unsupported or invalid reduction method '",
                                       reduction_method, "'"))
  assertthat::assert_that(is.logical(use_partition))
  assertthat::assert_that(is.logical(close_loop))
  assertthat::assert_that(is.logical(verbose))
  assertthat::assert_that(is.logical(orthogonal_proj_tip))
  assertthat::assert_that(is.logical(prune_graph))
  assertthat::assert_that(is.logical(scale))
  assertthat::assert_that(is.numeric(euclidean_distance_ratio))
  assertthat::assert_that(is.numeric(geodesic_distance_ratio))
  assertthat::assert_that(is.numeric(minimal_branch_len))
  if (!is.null(ncenter)) {
    assertthat::assert_that(assertthat::is.count(ncenter))
  }
  assertthat::assert_that(assertthat::is.count(maxiter))
  assertthat::assert_that(assertthat::is.count(rann.k))
  assertthat::assert_that(is.numeric(eps))
  assertthat::assert_that(is.numeric(L1.sigma))
  assertthat::assert_that(is.numeric(L1.sigma))
  assertthat::assert_that(!is.null(reducedDims(cds)[[reduction_method]]),
                          msg = paste("No dimensionality reduction for", reduction_method,
                                      "calculated.", "Please run reduce_dimension with",
                                      "reduction_method =", reduction_method, "and cluster_cells before running",
                                      "learn_graph."))
  assertthat::assert_that(!is.null(cds@clusters[[reduction_method]]),
                          msg = paste("No cell clusters for", reduction_method,
                                      "calculated.", "Please run cluster_cells with", "reduction_method =",
                                      reduction_method, "before running learn_graph."))
  if (use_partition) {
    partition_list <- cds@clusters[[reduction_method]]$partitions
  }
  else {
    partition_list <- rep(1, nrow(colData(cds)))
  }
  multi_tree_DDRTree_res <- monocle3:::multi_component_RGE(cds, scale = scale,
                                                           reduction_method = reduction_method, partition_list = partition_list,
                                                           irlba_pca_res = reducedDims(cds)[[reduction_method]],
                                                           max_components = max_components, ncenter = ncenter, rann.k = rann.k,
                                                           maxiter = maxiter, eps = eps, L1.gamma = L1.gamma, L1.sigma = L1.sigma,
                                                           close_loop = close_loop, euclidean_distance_ratio = euclidean_distance_ratio,
                                                           geodesic_distance_ratio = geodesic_distance_ratio, prune_graph = prune_graph,
                                                           minimal_branch_len = minimal_branch_len, verbose = verbose)
  rge_res_W <- multi_tree_DDRTree_res$ddrtree_res_W
  rge_res_Z <- multi_tree_DDRTree_res$ddrtree_res_Z
  rge_res_Y <- multi_tree_DDRTree_res$ddrtree_res_Y
  cds <- multi_tree_DDRTree_res$cds
  dp_mst <- multi_tree_DDRTree_res$dp_mst
  principal_graph(cds)[[reduction_method]] <- dp_mst
  cds@principal_graph_aux[[reduction_method]]$dp_mst <- rge_res_Y
  cds <- project2MST(cds, monocle3:::project_point_to_line_segment, orthogonal_proj_tip,
                     verbose, reduction_method, rge_res_Y)
  cds
}
project2MST <- function (cds, Projection_Method, orthogonal_proj_tip = FALSE, verbose, reduction_method, rge_res_Y) {
  dp_mst <- principal_graph(cds)[[reduction_method]]
  Z <- t(reducedDims(cds)[[reduction_method]])
  Y <- rge_res_Y
  cds <- monocle3:::findNearestPointOnMST(cds, reduction_method, rge_res_Y)
  closest_vertex <- cds@principal_graph_aux[[reduction_method]]$pr_graph_cell_proj_closest_vertex
  closest_vertex_names <- colnames(Y)[closest_vertex[, 1]]
  tip_leaves <- names(which(igraph::degree(dp_mst) == 1))
  if (!is.function(Projection_Method)) {
    P <- Y[, closest_vertex]
  } else {
    P <- matrix(rep(0, length(Z)), nrow = nrow(Z))
    nearest_edges <- matrix(rep(0, length(Z[1:2, ])), ncol = 2)
    row.names(nearest_edges) <- colnames(cds)
    for (i in 1:length(closest_vertex)) {
      neighbors <- names(igraph::neighborhood(dp_mst, nodes = closest_vertex_names[i],
                                              mode = "all")[[1]])[-1]
      projection <- NULL
      distance <- NULL
      Z_i <- Z[, i]
      for (neighbor in neighbors) {
        if (closest_vertex_names[i] %in% tip_leaves) {
          if (orthogonal_proj_tip) {
            tmp <- projPointOnLine(Z_i, Y[, c(closest_vertex_names[i],
                                              neighbor)])
          }
          else {
            tmp <- Projection_Method(Z_i, Y[, c(closest_vertex_names[i],
                                                neighbor)])
          }
        }
        else {
          tmp <- Projection_Method(Z_i, Y[, c(closest_vertex_names[i],
                                              neighbor)])
        }
        if (any(is.na(tmp))) {
          tmp <- Y[, neighbor]
        }
        projection <- rbind(projection, tmp)
        distance <- c(distance, stats::dist(rbind(Z_i,
                                                  tmp)))
      }
      if (class(projection)[1] != "matrix") {
        projection <- as.matrix(projection)
      }
      which_min <- which.min(distance)
      if (length(which_min) == 0)
        browser()
      P[, i] <- projection[which_min, ]
      nearest_edges[i, ] <- c(closest_vertex_names[i],
                              neighbors[which_min])
    }
  }
  colnames(P) <- colnames(Z)
  dp_mst_list <- igraph::decompose.graph(dp_mst)
  dp_mst_df <- NULL
  partitions <- cds@clusters[[reduction_method]]$partitions
  assertthat::assert_that(!is.null(names(cds@clusters[[reduction_method]]$partitions)),
                          msg = "names(cds@clusters[[reduction_method]]$partitions) == NULL")
  assertthat::assert_that(!(length(colnames(cds)) != length(names(cds@clusters[[reduction_method]]$partitions))),
                          msg = "length( colnames(cds) ) != length(names(cds@clusters[[reduction_method]]$partitions))")
  assertthat::assert_that(!any(colnames(cds) != names(cds@clusters[[reduction_method]]$partitions)),
                          msg = "colnames(cds)!=names(cds@clusters[[reduction_method]]$partitions)")
  if (length(dp_mst_list) == 1 && max( as.integer( levels( partitions))) >
      1) {
    levels( partitions)[ as.numeric( levels( partitions)) != '1'] <- '1'
  }
  if (!is.null(partitions)) {
    for (cur_partition in sort(unique(partitions))) {
      data_df <- NULL
      if (verbose) {
        message("\nProjecting cells to principal points for partition: ",
                cur_partition)
      }
      subset_cds_col_names <- names(partitions[partitions ==
                                               cur_partition])
      cur_z <- Z[, subset_cds_col_names]
      cur_p <- P[, subset_cds_col_names]
      if (ncol(cur_p) > 0 && nrow(cur_p) > 0) {
        ##cur_centroid_name <- igraph::V(dp_mst_list[[as.numeric(cur_partition)]])$name
        cur_centroid_name <- igraph::V(dp_mst_list[[1]])$name
        cur_nearest_edges <- nearest_edges[subset_cds_col_names,
                                           ]
        data_df <- cbind(as.data.frame(t(cur_p)), apply(cur_nearest_edges,
                                                        1, sort) %>% t())
        row.names(data_df) <- colnames(cur_p)
        colnames(data_df) <- c(paste0("P_", 1:nrow(cur_p)),
                               "source", "target")
        data_df$distance_2_source <- sqrt(colSums((cur_p -
                                                   rge_res_Y[, as.character(data_df[, "source"])])^2))
        data_df <- data_df %>% tibble::rownames_to_column() %>%
          dplyr::mutate(group = paste(source, target,
                                      sep = "_")) %>% dplyr::arrange(group, dplyr::desc(-distance_2_source))
        data_df <- data_df %>% dplyr::group_by(group) %>%
          dplyr::mutate(new_source = dplyr::lag(rowname),
                        new_target = rowname)
        data_df[is.na(data_df$new_source), "new_source"] <- as.character(as.matrix(data_df[is.na(data_df$new_source),
                                                                                           "source"]))
        added_rows <- which(is.na(data_df$new_source) &
                            is.na(data_df$new_target))
        data_df <- as.data.frame(data_df, stringsAsFactors = F)
        data_df <- as.data.frame(as.matrix(data_df),
                                 stringsAsFactors = F)
        data_df[added_rows, c("new_source", "new_target")] <- data_df[added_rows -
                                                                      1, c("rowname", "target")]
        aug_P = cbind(cur_p, rge_res_Y)
        data_df$weight <- sqrt(colSums((aug_P[, data_df$new_source] -
                                        aug_P[, data_df$new_target]))^2)
        data_df$weight <- data_df$weight + min(data_df$weight[data_df$weight >
                                                              0])
        edge_list <- as.data.frame(igraph::get.edgelist(dp_mst_list[[as.numeric(cur_partition)]]),
                                   stringsAsFactors = FALSE)
        dp <- as.matrix(stats::dist(t(rge_res_Y)[cur_centroid_name,
                                                 ]))
        edge_list$weight <- dp[cbind(edge_list[, 1],
                                     edge_list[, 2])]
        colnames(edge_list) <- c("new_source", "new_target",
                                 "weight")
        dp_mst_df <- Reduce(rbind, list(dp_mst_df, data_df[,
                                                           c("new_source", "new_target", "weight")], edge_list))
      }
    }
  }
  dp_mst <- igraph::graph.data.frame(dp_mst_df, directed = FALSE)
  cds@principal_graph_aux[[reduction_method]]$pr_graph_cell_proj_tree <- dp_mst
  cds@principal_graph_aux[[reduction_method]]$pr_graph_cell_proj_dist <- P
  closest_vertex_df <- as.matrix(closest_vertex)
  row.names(closest_vertex_df) <- row.names(closest_vertex)
  cds@principal_graph_aux[[reduction_method]]$pr_graph_cell_proj_closest_vertex <- closest_vertex_df
  cds
}
```

**Comment by massisnascimento** [comment] 2022-02-25 03:57
@ieiwk this is fantastic! Thank you so much!

**Comment by aktzz** [comment] 2023-04-27 18:10
Hello, sorry to open this again. I got the following error while running the learn_graph and could not figure out the issue causing this. Please help!  

cds <- learn_graph(cds, use_partition = T)
#Error in igraph::graph.dfs(stree_ori, root = root_cell, mode = "all",  : 
 # unused argument (mode = "all")

**Comment by beata-malachowska** [comment] 2023-05-05 17:53
Hi, I was getting the error as mentioned in first post:
Error in t(reducedDims(cds)[[reduction_method]])[, data_df[, "source"]] :
 subscript out of bounds
I followed the instruction as above and changed the code, but now when I use learn_graph() and get the following error: 
Error in monocle3:::multi_component_RGE(cds, scale = scale, reduction_method = reduction_method,  : 
  unused argument (rann.k = rann.k)

I tried updating RANN package (I have v.2.6.1 ) and I use modified version of monocle3 1.3.1. Can you help?

**Comment by hamidghaedi** [comment] 2023-05-16 02:50
> Hello, sorry to open this again. I got the following error while running the learn_graph and could not figure out the issue causing this. Please help!
> 
> cds <- learn_graph(cds, use_partition = T) #Error in igraph::graph.dfs(stree_ori, root = root_cell, mode = "all", :
> 
> # unused argument (mode = "all")

Did you find a solution to this? I am facing similar issue

**Comment by angelasanzo** [comment] 2023-07-20 15:46
Hi there!

Although this error appears as "closed", it has happened to me as well a couple of times, especially when the segmentation I choose is not 1. I have tried changing manually the code that @ieiwk proposed (thanks), however, as @aktzz pointed out another error pops up.

Has anyone found a way to solve this? 

Thank you

**Comment by beata-malachowska** [comment] 2023-07-20 16:51
The solution that was given before is probably working , but I had some technical problems to implement it. However, after analyzing the solution I came to a conclusion that if the number of partition higher than 1 is causing a problem then just change it to 1 and it works. I did like below and I was able to run monocle3 for other partitions.
integrated.sub <- subset(x, monocle3_partitions == 2)
integrated.sub@meta.data$monocle3_partitions <- 1

**Comment by apal6** [comment] 2023-08-07 19:34
Hi, I got the following error: 

`cds_from_seurat <- learn_graph(cds_from_seurat,  use_partition = T)
Error in multi_component_RGE(cds, scale = scale, reduction_method = reduction_method,  : 
  object 'rge_res' not found`

Not sure if anyone else has figured out this?

Thank you

**Comment by paulitikka** [comment] 2023-08-30 12:06
Hi,
Regarding 'unused argument (mode = "all")', add the name of the package to be used before the function first, e.g.:
deg <- igraph::degree(net, mode="all") 
#as in: # https://www.geeksforgeeks.org/how-to-fix-error-in-select-unused-arguments-in-r/
B.r.,
Pauli
